"""Modificar size_id

Revision ID: 0cc1cdeccfc6
Revises: afe252012d05
Create Date: 2024-03-06 19:18:54.330170

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0cc1cdeccfc6'
down_revision = 'afe252012d05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.alter_column('size_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('status_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('size', schema=None) as batch_op:
        batch_op.alter_column('size',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('size', schema=None) as batch_op:
        batch_op.alter_column('size',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.alter_column('status_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('size_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
