"""Add Rigs

Revision ID: 2948ba93731b
Revises: 75e18c5b2583
Create Date: 2024-02-06 19:27:18.488397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2948ba93731b'
down_revision = '75e18c5b2583'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rig_number', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rig_component_association',
    sa.Column('rig_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['component.id'], ),
    sa.ForeignKeyConstraint(['rig_id'], ['rig.id'], ),
    sa.PrimaryKeyConstraint('rig_id', 'component_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rig_component_association')
    op.drop_table('rig')
    # ### end Alembic commands ###
