"""Add rigger field on rigging

Revision ID: 3a8057cdc0dd
Revises: 6c5b9f0c52be
Create Date: 2024-03-16 22:09:45.137400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a8057cdc0dd'
down_revision = '6c5b9f0c52be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rigging', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rigger_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['rigger_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rigging', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('rigger_id')

    # ### end Alembic commands ###
