"""Modyfy RiggingType

Revision ID: 3cfb6ae26195
Revises: b33192447b6c
Create Date: 2024-03-31 13:47:17.710424

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3cfb6ae26195'
down_revision = 'b33192447b6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rigging_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rigging', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_rigging_id', sa.Integer(), nullable=False))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rigging', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_rigging', mysql.ENUM('INSPECTION_REPACK', 'REPARATION', 'ALTERATION', 'FABRICATION'), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('type_rigging_id')

    op.drop_table('rigging_type')
    # ### end Alembic commands ###
