"""Add role admin

Revision ID: 563aace16f79
Revises: 73a59447ac61
Create Date: 2024-03-10 18:15:54.514938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '563aace16f79'
down_revision = '73a59447ac61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
