"""Add types table

Revision ID: 56689f4bee63
Revises: bfed0b8cc1b7
Create Date: 2024-02-01 20:02:51.103230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56689f4bee63'
down_revision = 'bfed0b8cc1b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('component_type')
    # ### end Alembic commands ###
