"""Initial migration

Revision ID: 8bf13209f1cd
Revises: 
Create Date: 2024-05-28 15:06:12.790449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bf13209f1cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jumps', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('aad_jumps_on_mount', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.drop_column('aad_jumps_on_mount')
        batch_op.drop_column('jumps')

    # ### end Alembic commands ###
