"""Add fields to component - rig

Revision ID: afe252012d05
Revises: 2948ba93731b
Create Date: 2024-02-07 18:11:15.508268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe252012d05'
down_revision = '2948ba93731b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rig_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'rig', ['rig_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('rig_id')

    # ### end Alembic commands ###
