"""Add type_rigging to Rigging

Revision ID: b33192447b6c
Revises: 3a8057cdc0dd
Create Date: 2024-03-18 17:40:46.882509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b33192447b6c'
down_revision = '3a8057cdc0dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rigging', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_rigging', sa.Enum('INSPECTION_REPACK', 'REPARATION', 'ALTERATION', 'FABRICATION', name='riggingtype'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rigging', schema=None) as batch_op:
        batch_op.drop_column('type_rigging')

    # ### end Alembic commands ###
