"""Modify COmponent model

Revision ID: c90a986ddce9
Revises: d6a20e4dafd1
Create Date: 2024-05-29 15:58:17.623440

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c90a986ddce9'
down_revision = 'd6a20e4dafd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.drop_constraint('component_ibfk_4', type_='foreignkey')
        batch_op.drop_column('rig_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rig_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('component_ibfk_4', 'rig', ['rig_id'], ['id'])

    # ### end Alembic commands ###
