"""Add current_aad_jumps to class Rig

Revision ID: d6a20e4dafd1
Revises: 8bf13209f1cd
Create Date: 2024-05-28 18:45:57.796614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6a20e4dafd1'
down_revision = '8bf13209f1cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rig', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_aad_jumps', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rig', schema=None) as batch_op:
        batch_op.drop_column('current_aad_jumps')

    # ### end Alembic commands ###
