"""Modify type_rigging

Revision ID: f8d8922c1eeb
Revises: 3cfb6ae26195
Create Date: 2024-03-31 19:27:43.709660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8d8922c1eeb'
down_revision = '3cfb6ae26195'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rigging', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'rigging_type', ['type_rigging_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rigging', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
